---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nixys
spec:
  interval: 1m
  provider: ${HELM_REGISTRY_PROVIDER}
  type: ${HELM_REGISTRY_TYPE}
  url: ${HELM_REGISTRY_TYPE/default/http}://${HELM_REGISTRY_URL}${HELM_REGISTRY_HELM_CHARTS_REPOSITORY_PREFIX}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connectors-management
spec:
  releaseName: connectors-management
  chart:
    spec:
      chart: nxs-universal-chart
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: nixys
      interval: 1m
  interval: 1m
  timeout: 3m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    force: false
  valuesFrom:
    - kind: ConfigMap
      name: 00-connectors-management-helm-chart-default-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: 02-connectors-management-helm-chart-override-values
      valuesKey: values.yaml
