---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-connectors-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-connectors
  name: nginx-connectors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-connectors
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-connectors
    spec:
      containers:
      - image: qa.int.stratio.com/nginx:1.17.6-alpine
        name: nginx
        resources: {}
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-connectors-data
      volumes:
        - name: nginx-connectors-data
          persistentVolumeClaim:
            claimName: nginx-connectors-data
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-connectors
  name: nginx-connectors
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-connectors
  type: ClusterIP
