---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nixys
spec:
  interval: 1m
  provider: aws
  type: oci
  url: oci://${CONTAINER_REGISTRY_URL}${CONTAINER_REGISTRY_HELM_CHARTS_REPOSITORY_PREFIX}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-connectors
spec:
  releaseName: nginx-connectors
  chart:
    spec:
      chart: nxs-universal-chart
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: nixys
      interval: 1m
  interval: 1m
  timeout: 3m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    force: false
  valuesFrom:
    - kind: ConfigMap
      name: 00-nginx-connectors-helm-chart-default-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: 02-nginx-connectors-helm-chart-override-values
      valuesKey: values.yaml
