---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 00-nginx-connectors-helm-chart-default-values
data:
  values.yaml: |
    ---
    releasePrefix: "-"
    deployments:
      nginx-connectors:
        labels:
          app: nginx-connectors
        podLabels: {}
        podAnnotations: {}
        replicas: 1
        extraSelectorLabels:
          app: nginx-connectors
        serviceAccountName: ""
        initContainers:
          - name: connector-downloader
            image: amazon/aws-cli
            command: ["sh", "-c", "aws s3 cp s3://stratio-universe-artifacts/universe-14.7.0-5207e9c/connectors/sscc-s3-0.3_2.12-1.3.3-a14adae.jar /connector/sscc-s3-0.3_2.12-1.3.3-a14adae.jar"]
            envFrom:
              - secretRef:
                  name: nginx-connectors-s3
            volumeMounts:
            - name: connector
              mountPath: "/connector"
        containers:
          - name: nginx
            image: nginx
            imageTag: alpine
            env: []
            envsFromSecret: {}
            envSecrets: []
            envsFromConfigmap: {}
            envConfigmaps: []
            volumeMounts:
              - name: connector
                mountPath: /usr/share/nginx/html
        volumes:
          - name: connector
            type: emptyDir
    pvcs:
      nginx-connectors-data:
        accessModes:
          - ReadWriteOnce
        size: 1Gi
    services:
      nginx-connectors:
        clusterIP: None
        ports:
          - name: 80-80
            port: 80
            protocol: TCP
            targetPort: 80
        extraSelectorLabels:
          app: nginx-connectors
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 02-nginx-connectors-helm-chart-override-values
data:
  values.yaml: ""