---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 00-nginx-connectors-helm-chart-default-values
data:
  values.yaml: |
    ---
    releasePrefix: "-"
    deployments:
      nginx-connectors:
        labels:
          app: nginx-connectors
        podLabels: {}
        podAnnotations: {}
        replicas: 1
        extraSelectorLabels:
          app: nginx-connectors
        serviceAccountName: ""
        initContainers:
          - name: connector-downloader
            image: qa.int.stratio.com/curlimages/curl
            command: ["sh", "-c", "curl -sSfL http://qa.int.stratio.com/repository/new-releases/com/stratio/connectors/sscc-s3-0.3_2.12/1.3.3-a14adae/sscc-s3-0.3_2.12-1.3.3-a14adae.jar -o /connector/sscc-s3-0.3_2.12-1.3.3-a14adae.jar"]
            volumeMounts:
            - name: connector
              mountPath: "/connector"
        containers:
          - name: nginx
            image: nginx:alpine
            env: []
            envsFromSecret: {}
            envSecrets: []
            envsFromConfigmap: {}
            envConfigmaps: []
            volumeMounts:
              - name: connector
                mountPath: /usr/share/nginx/html
        volumes:
          - name: connector
            type: emptyDir
    pvcs:
      nginx-connectors-data:
        accessModes:
          - ReadWriteOnce
        size: 1Gi
    services:
      nginx-connectors:
        clusterIP: None
        ports:
          - name: 80-80
            port: 80
            protocol: TCP
            targetPort: 80
        extraSelectorLabels:
          app: nginx-connectors
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 02-nginx-connectors-helm-chart-override-values
data:
  values.yaml: ""