---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nixys
spec:
  interval: 1m
  provider: generic
  type: default
  url: https://registry.nixys.io/chartrepo/public
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pg-gosec-agent
spec:
  releaseName: pg-gosec-agent
  chart:
    spec:
      chart: nxs-universal-chart
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: nixys
      interval: 1m
  interval: 1m
  timeout: 3m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    force: false
  valuesFrom:
    - kind: ConfigMap
      name: 00-pg-gosec-agent-helm-chart-default-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: 02-pg-gosec-agent-helm-chart-override-values
      valuesKey: values.yaml
